[project]
name = "vkompililo-project"
version = "1.0.dev"

[tool.isort]
profile = "black"
float_to_top = true
# because hacking/flake8' H306 wants it:
# H306: imports not in alphabetical order
force_sort_within_sections = true
